name: CI
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  dependencies:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        mix_env: [dev, test]
        elixir: [1.13]
        otp: [24]
    env:
      MIX_ENV: ${{ matrix.mix_env }}
    steps:
      - uses: styfle/cancel-workflow-action@0.9.0
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        with:
          elixir-version: ${{ matrix.elixir }}
          otp-version: ${{ matrix.otp }}
      - uses: actions/cache@v2
        id: mix-cache
        with:
          path: |
            _build
            deps
          key: ${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-${{ hashFiles('mix.lock') }}-${{ matrix.mix_env }}
      - run: |
          mix deps.get
          mix deps.unlock --check-unused
          mix local.rebar --force
          mix local.hex --force
          mix deps.compile
          mix dialyzer --plt
        if: steps.mix-cache.outputs.cache-hit != 'true'

  static-code-analysis:
    needs: dependencies
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        mix_env: [dev, test]
        elixir: [1.13]
        otp: [24]
    env:
      MIX_ENV: ${{ matrix.mix_env }}
    steps:
      - uses: styfle/cancel-workflow-action@0.9.0
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        with:
          elixir-version: ${{ matrix.elixir }}
          otp-version: ${{ matrix.otp }}
      - uses: actions/cache@v2
        id: mix-cache
        with:
          path: |
            _build
            deps
          key: ${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-${{ hashFiles('mix.lock') }}-${{ matrix.mix_env }}
      - run: mix format --check-formatted
      - run: mix compile --warnings-as-errors
      - run: mix credo --strict
      - run: mix dialyzer --no-check --ignore-exit-status

  mix-test:
    needs: dependencies
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        mix_env: [dev, test]
        elixir: [1.13]
        otp: [24]
    env:
      MIX_ENV: ${{ matrix.mix_env }}
    steps:
      - uses: styfle/cancel-workflow-action@0.9.0
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        with:
          elixir-version: ${{ matrix.elixir }}
          otp-version: ${{ matrix.otp }}
      - uses: actions/cache@v2
        id: mix-cache
        with:
          path: |
            _build
            deps
          key: ${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-${{ hashFiles('mix.lock') }}-${{ matrix.mix_env }}
      - run: mix test --warnings-as-errors
      - run: mix test --no-start --slowest 10 --trace --warnings-as-errors
